name: Pull Request

# This workflow verifies that the site will build for pull requests.
on: [pull_request]

jobs:
  pull-request:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Run the tests.
    - name: Test
      run: make test

    # Ensure we can build.
    - name: Build
      run: make build

  shell-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [bash, dash]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install dash
      run: sudo apt-get update && sudo apt-get install -y dash
      if: matrix.shell == 'dash'
    
    - name: Test script with ${{ matrix.shell }}
      run: |
        # Set non-interactive mode and test script
        export ES_EXISTING_FOLDER_ACTION=d
        export ES_FORCE_INSTALL=1
        ${{ matrix.shell }} effective.sh
      env:
        ES_DEBUG: 1

