# The 'release-please' workflow is used to create the 'Release Please' pull
# request. This PR is opened when we have a new commit to master.
# See:
#   https://github.com/googleapis/release-please
name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # If the 'release please' action has been performed, we can actually
      # deploy the website.
      # Note: *every* step here needs to check the 'release_created' flag.
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      # Run the build.
      - name: Build
        run: make build
        if: ${{ steps.release.outputs.release_created }}

      # Deploy the website.
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
        if: ${{ steps.release.outputs.release_created }}
